name: Deploy Docusaurus Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # Updated to the latest version
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v3 # Updated to version 3
        with:
          node-version: "20" # Updated to Node.js 20

      - name: Install Dependencies
        run: |
          cd docs
          npm install

      - name: Build
        run: |
          cd docs
          npm run build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3 # Ensure you're using the latest version
        with:
          deploy_key: ${{ secrets.macbook }}
          publish_dir: ./docs/build
